# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Format-Flexible
version:      0.01
version_from: lib/DateTime/Format/Flexible.pm
installdirs:  site
requires:
    DateTime::Format::Builder:     0.74
    Readonly:                      0.06
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
