--- #YAML:1.0
name:                DateTime-Format-Flexible
version:             0.15
abstract:            DateTime::Format::Flexible - Flexibly parse strings and turn them into DateTime objects.
license:             perl
author:              
    - Tom Heady (cpan@punch.net)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DateTime:                      0
    DateTime::Format::Builder:     0.74
    DateTime::TimeZone:            0
    List::MoreUtils:               0
    Module::Pluggable:             0
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
