--- #YAML:1.0
name:               DateTime-Format-Flexible
version:            0.14
abstract:           DateTime::Format::Flexible - Flexibly parse strings and turn them into DateTime objects.
author:
    - Tom Heady (cpan@punch.net)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0
    DateTime::Format::Builder:  0.74
    DateTime::TimeZone:   0
    List::MoreUtils:      0
    Module::Pluggable:    0
    Test::Simple:         0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
